#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  14 December 2018                   #
#-------------------------------------------------#
# Topic:       Adaptive mesh refinement           #
# OpenFOAM:    6.x                                #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.de            #
# Email:       Tobias.Holzmann@Holzmann-cfd.de    #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-6.x"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#-------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
Note: You should have at least 4 GB free memory
"


#-------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv > logFile


#-------------------------------------------------------------------------------
echo -e "   - Copy STL for manipulation"
cp constant/triSurface/layer_orig.stl constant/triSurface/layer.stl
cp constant/triSurface/regionSTL_orig.stl constant/triSurface/regionSTL.stl


#------------------------------------------------------------------------------
echo -e "   - Scaling"
transformPoints -scale "(1000 1000 1000)" >> logFile
surfaceTransformPoints -scale "(1000 1000 1000)" con*/tri*/regionSTL.stl \
    con*/tri*/regionSTL.stl >> logFile
surfaceTransformPoints -scale "(1000 1000 1000)" con*/tri*/layer.stl \
    con*/tri*/layer.stl >> logFile


#------------------------------------------------------------------------------
echo -e "   - Create feature edges"
surfaceFeatureExtract >> logFile


#------------------------------------------------------------------------------
echo -e "   - Decompose mesh"
decomposePar >> logFile


#------------------------------------------------------------------------------
echo -e "   - Castallate and snap"
mpirun -np 2 snappyHexMesh -overwrite -parallel>> logFile


#------------------------------------------------------------------------------
echo -e "   - Change mesh quality parameters"
cp system/mesh*.layer system/meshQualityDict
sed '19s/.*/castellatedMesh false;/' sys*/snappyHexMeshDict -i
sed '20s/.*/snap false;/' sys*/snappyHexMeshDict -i
sed '21s/.*/addLayers true;/' sys*/snappyHexMeshDict -i


#------------------------------------------------------------------------------
echo -e "   - Add layerer with snappyHexMesh (Coverage: 95,4%)"
mpirun -np 2 snappyHexMesh -overwrite -parallel>> logFile


#------------------------------------------------------------------------------
echo -e "   - Change mesh quality parameters"
cp system/mesh*.normal system/meshQualityDict
sed -e '19s/.*/castellatedMesh true;/' sys*/snappyHexMeshDict -i
sed -e '20s/.*/snap true;/' sys*/snappyHexMeshDict -i
sed -e '21s/.*/addLayers false;/' sys*/snappyHexMeshDict -i


#------------------------------------------------------------------------------
echo -e "   - Reconstruct mesh"
reconstructParMesh -mergeTol 1e-6 -constant >> logFile
#rm -r proces*


#------------------------------------------------------------------------------
echo -e "   - Remove patches with zero faces"
createPatch -overwrite >> logFile


#------------------------------------------------------------------------------
echo -e "   - Scaling"
transformPoints -scale "(1e-3 1e-3 1e-3)" >> logFile
surfaceTransformPoints -scale "(0.001 0.001 0.001)" con*/tri*/regionSTL.stl \
    con*/tri*/regionSTL.stl >> logFile
surfaceTransformPoints -scale "(0.001 0.001 0.001)" con*/tri*/layer.stl \
    con*/tri*/layer.stl >> logFile


#------------------------------------------------------------------------------
echo -e "   - check the mesh (get errors): "
checkMesh -constant | egrep '\*[A-Z].*'


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n\n"


#-------------------------------------------------------------------------------
