#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  10 Februar 2025                    #
#-------------------------------------------------#
# Topic:       Simple case with cyclic BC (FAN)   #
# OpenFOAM:    version 12 (Foundation)            #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.com           #
# Email:       community@Holzmann-cfd.com         #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-12"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
if [ -f cad/backgroundMesh.unv ];
then
    echo "  - Background mesh exist, proceed..."
else
    echo "  - No background mesh exist, please build one"
    echo ""
    exit
fi


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "  - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv > logMeshing


#------------------------------------------------------------------------------
echo -e "  - Meshing with snappyHexMesh (generate internal faces)"
snappyHexMesh -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "  - Convert internal faces to baffles"
createBaffles -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n
"


#------------------------------------------------------------------------------
echo -e "  - Copy 0.orig to 0"
rm -rf 0
cp -r 0.orig 0


#------------------------------------------------------------------------------
echo -e "  - Initialize water level"
setFields > logSolve


#--------------------------------------------------------------------------
echo -e "  - Decompose the stuff"
decomposePar >> logSolve


#--------------------------------------------------------------------------
echo -e "  - Get number of processors in use"
nProcs=$(foamDictionary system/decomposeParDict -entry numberOfSubdomains -value)


#--------------------------------------------------------------------------
echo -e "  - Renumber the mesh for speedup"
mpirun -np $nProcs renumberMesh -overwrite -parallel -noZero -constant \
    >> logSolve


#--------------------------------------------------------------------------
echo -en "  - Manipulate controlDict: "
foamDictionary system/controlDict -entry endTime -set 10


#--------------------------------------------------------------------------
echo -e "  - Start filling (several hours ~ 10h)"
mpirun -np $nProcs foamRun -parallel >> logSolve


#--------------------------------------------------------------------------
echo -e "  - Reconstruct latest time"
reconstructPar -latestTime >> logSolve


#--------------------------------------------------------------------------
echo -e "  - Change boundary condition for U and p"
changeDictionary -latestTime >> logSolve


#--------------------------------------------------------------------------
echo -e "  - Update fields on processors"
decomposePar -fields -latestTime >> logSolve


#--------------------------------------------------------------------------
echo -en "  - Manipulate controlDict: "
foamDictionary system/controlDict -entry endTime -set 30


#--------------------------------------------------------------------------
echo -e "  - Start pumping + filling (several hours ~ 10h)"
mpirun -np $nProcs foamRun -parallel >> logSolve


#------------------------------------------------------------------------------
echo -e "  - End\n\n"


#------------------------------------------------------------------------------
