#!/bin/bash
#
#----------------------------------------------#
# Contributor: Tobias Holzmann                 #
# Last Change: October 2015                    #
# Topic:                                       #
# Email:       Tobias.Holzmann@Holzmann-cfd.de #
#----------------------------------------------#


#-------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear


#-------------------------------------------------------------------------------
foamCleanTutorials
rm -f constant/triSurface/*.eMesh paraview.foam
rm -rf 0 log* constant/extend*


#-------------------------------------------------------------------------------
