#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  15 September 2018                  #
#-------------------------------------------------#
# Topic:       Community Cristmas Competition     #
# OpenFOAM:    5.x                                #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.de            #
# Email:       Tobias.Holzmann@Holzmann-cfd.de    #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-5.x"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
if [ -f cad/backgroundMesh.unv ];
then
    echo "   - Background mesh exist, proceed..."
else
    echo "   - No background mesh exist, please create one'"
    echo ""
    exit
fi


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv > logMeshing


#------------------------------------------------------------------------------
echo -e "   - Meshing with snappyHexMesh (~ 5 minutes)"
decomposePar >> logMeshing
mpirun -np 4 snappyHexMesh -parallel -overwrite >> logMeshing
reconstructParMesh -constant >> logMeshing
transformPoints -scale "(0.1 0.1 0.1)" >> logMeshing


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n
"


#------------------------------------------------------------------------------
echo -e "   - Copy 0.orig to 0"
rm -r 0
cp -r 0.orig 0


#------------------------------------------------------------------------------
echo -e "   - Start simulation"
echo -e "   - Decompose the case for parallel run"
decomposePar -force > logSolver


#------------------------------------------------------------------------------
echo -e "   - Renumber mesh for speedup (~5-15%)"
mpirun -np 4 renumberMesh -overwrite -parallel >> logSolver


#------------------------------------------------------------------------------
echo -e "   - Start transient calculation (1-2 days to get the video result)"
mpirun -np 4 simpleFoam -parallel >> logSolver


#------------------------------------------------------------------------------
echo -e "   - Simulation ended\n\n"


#------------------------------------------------------------------------------
