#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  23 December 2018                   #
#-------------------------------------------------#
# Topic:       6DOF and AMI in Kaplan Turbine     #
# OpenFOAM:    6.x                                #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.de            #
# Email:       Tobias.Holzmann@Holzmann-cfd.de    #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-6.x"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
if [ -f cad/backgroundMesh.unv ];
then
    echo "   - Background mesh exist, proceed..."
else
    echo "   - No background mesh exist, please build one"
    echo ""
    exit
fi


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv > logMeshing


#------------------------------------------------------------------------------
echo -e "   - Decompose background mesh"
decomposePar >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Meshing using snappyHexMesh (~ 10 minutes)"
mpirun -np 4 snappyHexMesh -overwrite -parallel >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Reconstruct mesh"
reconstructParMesh -constant -mergeTol 1e-6 >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Modify boundaries for AMI"
createPatch -overwrite  >> logMeshing
rm -rf 0


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n
"


#------------------------------------------------------------------------------
echo -e "   - Copy 0.org to 0"
cp -r 0.org 0


#------------------------------------------------------------------------------
if [ `which pimpleFoam` ]
then
    #--------------------------------------------------------------------------
    echo -e "   - Decompose the mesh again"
    decomposePar > logSolve


    #--------------------------------------------------------------------------
    echo -e "   - Renumber the mesh again"
    mpirun -np 4 renumberMesh -overwrite -parallel >> logSolve


    #--------------------------------------------------------------------------
    echo -e "   - Start simulation (this will need a long time)"
    pimpleFoam > logSolve


    #--------------------------------------------------------------------------
else
    #--------------------------------------------------------------------------
    echo -en "   - Can not start simulation, '${RED}pimpleFoam$NC'"
    echo -e " not available"


    #--------------------------------------------------------------------------
fi


#------------------------------------------------------------------------------
echo -e "   - End\n\n"


#------------------------------------------------------------------------------
