#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  31 Juli 2020                       #
#-------------------------------------------------#
# Topic:       Sphere meshing with layers         #
# OpenFOAM:    version 8 (Foundation)             #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.com           #
# Email:       community@Holzmann-cfd.com         #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-8"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#-------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#-------------------------------------------------------------------------------
echo -e "   - Create STL files"
cat cad/stlChannel/* > constant/triSurface/channel.stl
cp cad/stlSphere/sphere.stl constant/triSurface/sphere.stl


#-------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv > logFile


#-------------------------------------------------------------------------------
echo -e "   - Create feature edges"
surfaceFeatures >> logFile


#-------------------------------------------------------------------------------
echo -e "   - Meshing the fluid domain with snappyHexMesh (cutting out the sphere)"
snappyHexMesh >> logFile


#-------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n\n
"


#-------------------------------------------------------------------------------
