#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  11 Februar 2025                    #
#-------------------------------------------------#
# Topic:       Simple case with cyclic BC (FAN)   #
# OpenFOAM:    version 12 (Foundation)            #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.com           #
# Email:       community@Holzmann-cfd.com         #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-12"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
if [ -f cad/backgroundMesh.unv ];
then
    echo "  - Background mesh exist, proceed..."
else
    echo "  - No background mesh exist, please build a mesh"
    echo ""
    exit
fi


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "  - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv > logMeshing


#------------------------------------------------------------------------------
echo -e "  - Meshing with snappyHexMesh (generate cellZones)"
snappyHexMesh -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "  - Split mesh into its different regions (based on cellZones)"
echo -e "    Note: If -defaultRegionName is not specified, the regions that"
echo -e "    do not containt to one cellZone goes to the default one named:"
echo -e "    >> region1 <<"
splitMeshRegions -cellZones -defaultRegionName air -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "  - Remove not needed meshes and dictionaries"
rm -rf constant/polyMesh constant/air constant/glass 0 system/air \
    system/glass constant/region* system/region*


#------------------------------------------------------------------------------
echo -e "  - Rename the boundary names (e.g., the connection to air which we"
echo -e "    dont have)"
createPatch -region ginTonic -overwrite > logMeshing
createPatch -region iceCube1 -overwrite >> logMeshing
createPatch -region iceCube2 -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "  - Copy 0.orig to 0"
rm -rf 0
cp -r 0.orig 0


#------------------------------------------------------------------------------
echo -e "  - Set up the correct boundary conditions and initial values"
changeDictionary -region ginTonic >> logMeshing
changeDictionary -region iceCube1 >> logMeshing
changeDictionary -region iceCube2 >> logMeshing


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n
"


#------------------------------------------------------------------------------
echo -e "  - Complete the thermodynamic stuff"
cd constant/ginTonic
ln -s ../thermoPropertiesFluid/* .
cd ../iceCube1
ln -s ../thermoPropertiesSolid/* .
cd ../iceCube2
ln -s ../thermoPropertiesSolid/* .
cd ../../


#--------------------------------------------------------------------------
echo -e "  - Get core numbers"
nC=$(foamDictionary system/decomposeParDict -entry numberOfSubdomains -value)


#--------------------------------------------------------------------------
echo -e "  - Decompose the stuff"
decomposePar -region ginTonic >> logSolve
decomposePar -region iceCube1 >> logSolve
decomposePar -region iceCube2 >> logSolve


#--------------------------------------------------------------------------
echo -e "  - Renumber the mesh"
mpirun -np $nC renumberMesh -region ginTonic -overwrite -parallel >> logSolve
mpirun -np $nC renumberMesh -region iceCube1 -overwrite -parallel >> logSolve
mpirun -np $nC renumberMesh -region iceCube2 -overwrite -parallel >> logSolve


#--------------------------------------------------------------------------
echo -e "  - Start simulation (a few hours)"
mpirun -np $nC foamMultiRun -parallel >> logSolve


#------------------------------------------------------------------------------
echo -e "  - End\n\n"


#------------------------------------------------------------------------------
