#!/bin/bash
#
#----------------------------------------------#
# Contributor: Tobias Holzmann                 #
# Last Change: November 2014                   #
# Topic:       Multiregion meshing             #
# Email:       Tobias.Holzmann@Holzmann-cfd.de #
#----------------------------------------------#


#-------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear


#-------------------------------------------------------------------------------
rm -rf logFile* c*/extend* c*/poly* 0 1 2 3 const*/tri*/*eMesh
foamCleanTutorials


#-------------------------------------------------------------------------------
