#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  15 September 2018                  #
#-------------------------------------------------#
# Topic:       Multiregion meshing                #
# OpenFOAM:    5.x                                #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.de            #
# Email:       Tobias.Holzmann@Holzmann-cfd.de    #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-5.x"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#-------------------------------------------------------------------------------
echo -e "   - Convert original featureEdges to eMesh"
surfaceFeatureConvert constant/triSurface/featureEdgesStandard.obj \
    constant/triSurface/featureEdges.eMesh > logFile



#-------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv >> logFile


#-------------------------------------------------------------------------------
echo -e "   - Meshing with snappyHexMesh" 
snappyHexMesh -overwrite >> logFile


#-------------------------------------------------------------------------------
echo -e "   - Copy mesh to time folder 1"
mkdir -p 1
mv 0/* 1/
cp -r con*/polyMesh 1/polyMesh
rm -r con*/polyMesh


#-------------------------------------------------------------------------------
echo -e "   - Meshing with standard edgeMesh DONE
"
rm -r 0


#-------------------------------------------------------------------------------
echo -e "   - Convert modified featureEdges to eMesh (build with Blender)"
surfaceFeatureConvert constant/triSurface/featureEdgesOptimized.obj \
    constant/triSurface/featureEdges.eMesh > logFileOptimized


#-------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv >> logFileOptimized


#-------------------------------------------------------------------------------
echo -e "   - Meshing with snappyHexMesh" 
snappyHexMesh -overwrite >> logFileOptimized


#-------------------------------------------------------------------------------
echo -e "   - Copy mesh to time folder 2"
mkdir -p 2
mv 0/* 2/
cp -r con*/polyMesh 2/polyMesh
rm -r con*/polyMesh 


#-------------------------------------------------------------------------------
echo -e "   - Meshing with optimized edgeMesh DONE
"
rm -r 0


#-------------------------------------------------------------------------------
echo -e "   - Convert original featureEdges to eMesh (build with Blender)"
surfaceFeatureConvert constant/triSurface/featureEdgesStandard.obj \
    constant/triSurface/featureEdges.eMesh > logFile


#-------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv >> logFile


#-------------------------------------------------------------------------------
echo -e "   - Changing snappyHexMeshDict -> levels (( )) instead of level"
sed -i 's/        level 2/        levels ((0.01 2))/g' sys*/snappyHexMeshDict


#-------------------------------------------------------------------------------
echo -e "   - Meshing with snappyHexMesh and levels (( ))" 
snappyHexMesh -overwrite >> logFile


#-------------------------------------------------------------------------------
echo -e "   - Copy mesh to time folder 3"
mkdir -p 3
mv 0/* 3/
cp -r con*/polyMesh 3/polyMesh
rm -r con*/polyMesh


#-------------------------------------------------------------------------------
echo -e "   - Rechange snappyHexMeshDict to original one" 
sed -i 's/        levels ((0.01 2))/        level 2/g' sys*/snappyHexMeshDict




#-------------------------------------------------------------------------------
echo -e "   - Meshing with standard edgeMesh and levels (( )) DONE"
rm -r 0
mkdir 0


#-------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n\n
"


#-------------------------------------------------------------------------------
