#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  27 Oktober 2024                    #
#-------------------------------------------------#
# Topic:       Multiregion meshing                #
# OpenFOAM:    version 12 (Foundation)            #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.com           #
# Email:       community@Holzmann-cfd.com         #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-12"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#-------------------------------------------------------------------------------
echo -e "   - Convert original featureEdges to eMesh"
echo -e "     This eMesh can be created by using surfaceFeature application"
surfaceFeatureConvert constant/triSurface/featureEdgesStandard.obj \
    constant/triSurface/featureEdges.eMesh > logFileFeatureEdges



#-------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv >> logFileFeatureEdges


#-------------------------------------------------------------------------------
echo -e "   - Meshing with snappyHexMesh"
snappyHexMesh -overwrite >> logFileFeatureEdges


#-------------------------------------------------------------------------------
echo -e "   - Copy mesh to time folder 1"
mkdir -p 1
mv 0/* 1/
cp -r con*/polyMesh 1/polyMesh
rm -r con*/polyMesh


#-------------------------------------------------------------------------------
echo -e "   - Meshing with standard edgeMesh DONE
"
rm -r 0


#-------------------------------------------------------------------------------
echo -e "   - Convert modified featureEdges to eMesh (build with Blender)"
surfaceFeatureConvert constant/triSurface/featureEdgesOptimized.obj \
    constant/triSurface/featureEdges.eMesh > logFileOptimized


#-------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv >> logFileOptimized


#-------------------------------------------------------------------------------
echo -e "   - Meshing with snappyHexMesh (eMesh from Blender)"
snappyHexMesh -overwrite >> logFileOptimized


#-------------------------------------------------------------------------------
echo -e "   - Copy mesh to time folder 2"
mkdir -p 2
mv 0/* 2/
cp -r con*/polyMesh 2/polyMesh
rm -r con*/polyMesh


#-------------------------------------------------------------------------------
echo -e "   - Meshing with optimized edgeMesh DONE
"
rm -r 0


#-------------------------------------------------------------------------------
echo -e "   - Convert original featureEdges to eMesh"
surfaceFeatureConvert constant/triSurface/featureEdgesStandard.obj \
    constant/triSurface/featureEdges.eMesh > logFileLevels


#-------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv >> logFileLevels


#-------------------------------------------------------------------------------
echo -e "   - Changing snappyHexMeshDict -> levels (( )) instead of level"
sed -i 's/        level 2/        levels ((0.01 2))/g' sys*/snappyHexMeshDict


#-------------------------------------------------------------------------------
echo -e "   - Meshing with snappyHexMesh and levels (( ))"
snappyHexMesh -overwrite >> logFileLevels


#-------------------------------------------------------------------------------
echo -e "   - Copy mesh to time folder 3"
mkdir -p 3
mv 0/* 3/
cp -r con*/polyMesh 3/polyMesh
rm -r con*/polyMesh


#-------------------------------------------------------------------------------
echo -e "   - Recreate the background mesh for paraview"
ideasUnvToFoam cad/backgroundMesh.unv >> logFileLevels


#-------------------------------------------------------------------------------
echo -e "   - Rechange snappyHexMeshDict to original one"
sed -i 's/        levels ((0.01 2))/        level 2/g' sys*/snappyHexMeshDict




#-------------------------------------------------------------------------------
echo -e "   - Meshing with standard edgeMesh and levels (( )) DONE"
rm -r 0
mkdir 0


#-------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n\n
"


#-------------------------------------------------------------------------------
