#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  10 Februar 2025                    #
#-------------------------------------------------#
# Topic:       Convert fluent mesh for CHT mesh   #
# OpenFOAM:    version 12 (Foundation)            #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.com           #
# Email:       community@Holzmann-cfd.com         #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-12"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
echo -e "  - Convert fluent mesh to a foam mesh and write sets"
fluentMeshToFoam cad/fluentMesh.cas -writeSets > logMeshing


#------------------------------------------------------------------------------
echo -e "  - Convert  cellZonesSets to cellZones"
topoSet -constant >> logMeshing


#------------------------------------------------------------------------------
echo -e "  - Split mesh based on cellZones to get two regions"
splitMeshRegions -cellZonesOnly -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "  - Clean not necessary files"
rm -r 0 constant/polyMesh constant/cellToRegion


#------------------------------------------------------------------------------
echo -e "  - Mesh converted successfully\n"


#------------------------------------------------------------------------------
echo -e "  - Create file for paraview"
touch paraview.foam


#------------------------------------------------------------------------------
echo -e "  - Use '${FL}paraFoam -region fluid$NC' to display the fluid region"
echo -e "  - Use '${FL}paraFoam -region solid$NC' to display the solid region"
echo -e "  - Use '${FL}paraview paraview.foam$NC' to display both region\n\n"


#------------------------------------------------------------------------------
