#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  19 Oktober 2024                    #
#-------------------------------------------------#
# Topic:       Community Cristmas Competition     #
# OpenFOAM:    version 12 (Foundation)             #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.com           #
# Email:       community@Holzmann-cfd.com         #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-12"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble

cd 2D_0msto50ms

#------------------------------------------------------------------------------
if [ -f cad/backgroundMesh.unv ];
then
    echo "   - Background mesh exist, proceed..."
else
    echo "   - No background mesh exist, please create one'"
    echo ""
    exit
fi


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv > logMeshing


#------------------------------------------------------------------------------
echo -e "   - Meshing with snappyHexMesh"
snappyHexMesh -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Update the boundary types of the patches"
changeDictionary >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Extrude the mesh to generate a 2D mesh"
extrudeMesh >> logMeshing


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n
"


#------------------------------------------------------------------------------
echo -e "   - Copy 0.orig to 0"
rm -r 0
cp -r 0.orig 0


#------------------------------------------------------------------------------
echo -e "   - Start simulation"
echo -e "   - Decompose the case for parallel run"
decomposePar -force > logSolver


#------------------------------------------------------------------------------
echo -e "   - Start transient calculation (2-3 days to get to 50 m/s)"
mpirun -np 2 foamRun -parallel >> logSolver


#------------------------------------------------------------------------------
echo -e "   - Simulation ended\n\n"
echo -e "   - For the others, create a symbolic link for the mesh"
echo -e "     and decompose the case. Afterwards start pimpleFoam. Enjoy"

cd ..

#------------------------------------------------------------------------------
