#!/bin/bash
#
#----------------------------------------------#
# Contributor: Tobias Holzmann                 #
# Last Change: October 2016                    #
# Topic:       DAKOTA coupling with OpenFOAM   #
# Email:       Tobias.Holzmann@Holzmann-cfd.de #
# Location:    www.Holzmann-cfd.de             #
#----------------------------------------------#


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear


#------------------------------------------------------------------------------
foamCleanTutorials
rm -rf constant/triSurface/*.eMesh optimizationLog Log analyse*
rm -rf 0 log* constant/extend* dakotaLog dakotaData* dakota.rst constant/poly*
rm -rf constant/triSurface/baffles1.stl system/dakotaParameters
rm -rf system/rotateBaffles Tmin Tmax Taverage constant/triS*/baffles2.stl
rm -rf results S4 *.out constant/triSurface/baffle1.stl
rm -rf cons*/triSu*/baffle2.stl system/dakotaParameter


#------------------------------------------------------------------------------
