#!/bin/bash
#
#----------------------------------------------#
# Contributor: Tobias Holzmann                 #
# Updated on:  30 September 2018                  #
# Topic:       DAKOTA coupling with OpenFOAM   #
# Email:       Tobias.Holzmann@Holzmann-cfd.de #
# OpenFOAM:    4.x                                #
#----------------------------------------------#
# Website:     https://Holzmann-cfd.de            #

# Color definition
#------------------------------------------------------------------------------
RED='\e[0;31m'
GREEN='\e[0;32m'
NC='\e[0m'
ORANGE='\033[0;33m'
FL='\033[0;36m'


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean

dakotaInputFile="system/dakotaDict"
dakotaOutputFile="dakotaLog"
optimizationLogFile="optimizationLog"


# Analyze stuff (Post-Processing)
#------------------------------------------------------------------------------
mkdir -p results
touch results/paraview.foam


#------------------------------------------------------------------------------
echo -en "
-------------------------------------------------------------------------------
${GREEN}Tutorial by Tobias Holzmann
Generated October 2016  
${ORANGE}OpenFOAM-4.x
DAKOTA
${RED}Tested with Ubuntu 16.04

${FL}Topic: DAKOTA coupling with OpenFOAM (mixing problem)
-------------------------------------------------------------------------------
${NC}++ Latin Hypercube Sampling (LHS) of three parameters:
++ change inlet size
++ change baffle angel of baffle 1
++ change baffle angel of baffle 2

Thanks to ${ORANGE}Harald Unger ${NC}for the idea of this kind of tutorial. 

In the following dakota coupling case, we mix a cold and hot stream that has to
be uniform distributed at the outlet and should reach a temperature of 320K. 
The parameter of the average temperature is set in dakota.sh. During the study
we will analyze a set of parameters that are choosen by the LHS method. After
that we could apply some optimization loop, but this is not the specification
of this tutorial. If you want to do this kind of simulation (optimization), 
you should check out the official dokumentation of DAKOTA.

${GREEN}++ NOTE:${NC}
   This tutorial is not about DAKOTA because the settings and solver that I am
   using are not the best one. The tutorial should demonstrate how we can
   couple the two software packages. Some hints about the scripts and files
   can be read in the README file.

${ORANGE}++ NOTE about the case:${NC}
   The case is high instationary, if the baffles block the flow. We will get
   vortex shedding, therefore the SIMPLE algorithm will not converge in 
   some cases based on the instationarity.
-------------------------------------------------------------------------------
\n
"


sleep 5


#------------------------------------------------------------------------------
echo -e "   - Lets start doing DAKOTA the work for us"
echo -e "     ++ Input file for dakota: $dakotaInputFile"
echo -e "     ++ Output file for dakota: $dakotaOutputFile"
echo -e "     ++ Log file: $optimizationLogFile"
echo -e "     ++ Average Temperature at outlet should be: $Tmean"


# Check for DAKOTA and start if found
#------------------------------------------------------------------------------
if [ `which dakota | grep 'dakota' -c` == 1 ];
then
    echo "1" > .optimizationLoop
    dakota -i $dakotaInputFile -o $dakotaOutputFile > $optimizationLogFile &
    echo -e "   - ${GREEN}DAKOTA found and is running ...${NC}\n"
    wait
else
    echo "   - ${RED}No dakota application available, skip DAKOTA${NC}\n\n"
    exit
fi


#------------------------------------------------------------------------------
echo -e "   - DAKOTA analyzes successfully ended\n\n"


# Clean the case a bit
#------------------------------------------------------------------------------
rm -fr Tmin Tmax Taverage dakota.rst S4 *.out postProcessing
mv LHS* results


#------------------------------------------------------------------------------
