#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  22 April 2020                      #
#-------------------------------------------------#
# Topic:       Heat Transfer                      #
# OpenFOAM:    7.x                                #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.com           #
# Email:       community@Holzmann-cfd.com         #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-7.x"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
if [ -f cad/backgroundMesh.unv ];
then
    echo "   - Background mesh exist, proceed..."
else
    echo "   - No background mesh exist, please build one"
    echo ""
    exit
fi


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv > logMeshing


#------------------------------------------------------------------------------
echo -e "   - Meshing using snappyHexMesh (~ 3 minute)"
snappyHexMesh -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n
"


#------------------------------------------------------------------------------
echo -e "   - Copy 0.org to 0"
rm -rf 0
cp -r 0.orig 0


#------------------------------------------------------------------------------
if ls -l $FOAM_USER_LIBBIN | grep -q 'libsolverTEGModule.so'
then

    #--------------------------------------------------------------------------
    echo -e "   - Decompose the mesh"
    decomposePar -force > logSolve


    #--------------------------------------------------------------------------
    echo -e "   - Renumber the mesh / important for big meshes -> speed-up"
    mpirun -np 4 renumberMesh -overwrite -parallel >> logSolve


    #--------------------------------------------------------------------------
    echo -e "   - Set the fields (different thermal conductivities)"
    mpirun -np 4 setFields -parallel >> logSolve


    #--------------------------------------------------------------------------
    echo -e "   - Start simulation with own solver module"
    mpirun -np 4 foamRun -parallel >> logSolve


    #--------------------------------------------------------------------------
else

    #--------------------------------------------------------------------------
    echo -en "   - Can not start simulation since solver module is missing"
    echo -e "     You have to compile the module first"


    #--------------------------------------------------------------------------
fi


#------------------------------------------------------------------------------
echo -e "   - End\n\n"


#------------------------------------------------------------------------------
