#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  11 Februar 2025                    #
#-------------------------------------------------#
# Topic:       Sneezing Simulation                #
# OpenFOAM:    version 12 (Foundation)            #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.com           #
# Email:       community@Holzmann-cfd.com         #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-12"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv > logMeshing


#------------------------------------------------------------------------------
echo -e "   - Decompose background mesh"
decomposePar >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Meshing with snappyHexMesh (~ 4 minutes)"
mpirun -np 8 snappyHexMesh -overwrite -parallel >> logMeshing


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n
"


#------------------------------------------------------------------------------
echo -e "   - Copy 0.org to processor* folders"
for p in $(ls -d processor*)
do
    rm -rf $p/0
    cp -r 0.orig $p/0
done


#------------------------------------------------------------------------------
echo -e "   - Renumbering the mesh (here we get an error due to dynamic code)"
echo -e "     I could not resolve the error up to now but the code works after"
echo -e "     we execute it the seonc time - maybe a bug or some code issue)"
mpirun -np 8 renumberMesh -overwrite -parallel > logSolver 2>&1


#------------------------------------------------------------------------------
echo -e "   - Start the calculation"
echo -e "     Note: Simulation performed using 8 cores in 24 h"
mpirun -np 8 foamRun -parallel >> logSolver


#------------------------------------------------------------------------------
echo -e "   - Simulation ended\n\n"


#------------------------------------------------------------------------------
