#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  10 Februar 2025                    #
#-------------------------------------------------#
# Topic:       AMI FAN Tutorial and SnappyHexMesh #
# OpenFOAM:    version 12 (Foundation)            #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.com           #
# Email:       community@Holzmann-cfd.com         #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-12"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv > logMeshing


#------------------------------------------------------------------------------
echo -e "   - Meshing with snappyHexMesh (~ 120 seconds)"
snappyHexMesh -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Create baffles for the nonConformal application"
createBaffles -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Split Baffles to allow sliding. If this step is not done, the"
echo -e "     moving and static mesh part are still connected"
splitBaffles -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Create nonConformal patches (interface)"
createNonConformalCouples -overwrite AMI1 AMI2 >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Renumber the mesh for optimizing the matrix"
renumberMesh -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n
"


#------------------------------------------------------------------------------
echo -e "   - Copy 0.orig to 0"
cp -r 0.orig 0


#------------------------------------------------------------------------------
echo -e "   - Decompose the case"
decomposePar > logSimulation


#------------------------------------------------------------------------------
echo -e "   - Start simulation (approximately 20h * 1.3)"
echo -e "     The NCC approach does make the simulation way slower but it is"
echo -e "     conservative compared to the old Arbitrary Mesh Interface (AMI)"
mpirun -np 4 foamRun -parallel >> logSimulation


#------------------------------------------------------------------------------
echo -e "   - Simulation ended\n\n"


#------------------------------------------------------------------------------
