#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  14 December 2018                   #
#-------------------------------------------------#
# Topic:       Meshing a pipe (45 degree)         #
# OpenFOAM:    6.x                                #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.de            #
# Email:       Tobias.Holzmann@Holzmann-cfd.de    #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-6.x"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Create feature edges"
surfaceFeatureExtract >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Scale background mesh"
transformPoints -scale "(1000 1000 1000)" >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Meshing with snappyHexMesh"
snappyHexMesh >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Scale background mesh"
transformPoints -scale "(1e-3 1e-3 1e-3)" >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Note 99.5% layers are generated. Changing the layer settings can"
echo -e "     result in a 100% of layer generation. Problem here is the outlet"
echo -e "     that causes tiny problems due to the fact that the mesh is "
echo -e "     built under 45°. A 90° pipe will have 100% without changing the"
echo -e "     layerControl parameters."


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n\n
"


#------------------------------------------------------------------------------
