#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on: 22 October 2017                     #
#-------------------------------------------------#
# Topic:       Meshing a pipe (45 degree)         #
# OpenFOAM:    5.x                                #
#-------------------------------------------------#
# Location:    www.Holzmann-cfd.de                #
# Email:       Tobias.Holzmann@Holzmann-cfd.de    #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-5.x"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Create feature edges"
surfaceFeatureExtract >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Scale background mesh"
transformPoints -scale "(1000 1000 1000)" >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Meshing with snappyHexMesh" 
snappyHexMesh -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Scale background mesh"
transformPoints -scale "(1e-3 1e-3 1e-3)" >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Note 99.5% layers are generated. Changing the layer settings can"
echo -e "     result in 100% of layer generation. Problem zone is the outlet"
echo -e "     that causes tiny problems due to the fact that the mesh is "
echo -e "     build under 45°. A 90° pipe will have 100% without changinthe"
echo -e "     layerControl parameters."


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n\n
"


#------------------------------------------------------------------------------
