#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  22 April 2020                      #
#-------------------------------------------------#
# Topic:       Bouyancy driven flows              #
# OpenFOAM:    7.x                                #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.com           #
# Email:       community@Holzmann-cfd.com         #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-7.x"
application="buoyantPimpleFoam"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
if [ -f cad/backgroundMesh.unv ];
then
    echo "   - Background mesh exist, proceed..."
else
    echo "   - No background mesh exist, please build one"
    echo ""
    exit
fi


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv > logMeshing


#------------------------------------------------------------------------------
echo -e "   - Meshing using snappyHexMesh (~ 5 minute)"
snappyHexMesh -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Cleaning"
rm -rf 0


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n
"


#------------------------------------------------------------------------------
echo -e "   - Copy 0.org to 0"
cp -r 0.orig 0


#------------------------------------------------------------------------------
if [ `which $application` ]
then

    #--------------------------------------------------------------------------
    echo -e "   - Get number of cores"
    nCores=`cat system/decomposeParDict | grep 'numberOfSubdomains' | xargs \
        | cut -d' ' -f2 | tr ';' ' ' | xargs`



    #--------------------------------------------------------------------------
    echo -e "   - Decompose the mesh"
    decomposePar > logSolve


    #--------------------------------------------------------------------------
    echo -e "   - Renumber the mesh again"
    mpirun -np $nCores renumberMesh -overwrite -parallel >> logSolve


    #--------------------------------------------------------------------------
    echo -e "   - Start simulation (this will take one day)"
    mpirun -np $nCores $application -parallel >> logSolve


    #--------------------------------------------------------------------------
else

    #--------------------------------------------------------------------------
    echo -en "   - Can not start simulation, '${RED}${application}$NC'"
    echo -e " not available"


    #--------------------------------------------------------------------------
fi


#------------------------------------------------------------------------------
echo -e "   - End\n\n"


#------------------------------------------------------------------------------
