#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  19 Oktober 2024                    #
#-------------------------------------------------#
# Topic:       Community Cristmas Competition     #
# OpenFOAM:    version 12 (Foundation)             #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.com           #
# Email:       community@Holzmann-cfd.com         #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-12"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
if [ -f cad/backgroundMesh.unv ];
then
    echo "   - Background mesh exist, proceed..."
else
    echo "   - No background mesh exist, please create one'"
    echo ""
    exit
fi


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv > logMeshing


#------------------------------------------------------------------------------
echo -e "   - Decompose the mesh"
decomposePar >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Meshing with snappyHexMesh (~ 5 minutes)"
mpirun -np 4 snappyHexMesh -parallel -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Check the mesh for analysis"
mpirun -np 4 checkMesh -parallel >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Scale the mesh to correct dimensions"
mpirun -np 4 transformPoints "scale=(0.1 0.1 0.1)" -parallel >> logMeshing


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n
"


#------------------------------------------------------------------------------
echo -e "   - Copy 0.orig to processor*/0"
for i in $(ls -d proc*)
do
    rm -rf $i/0
    cp -r 0.orig $i/0
done


#------------------------------------------------------------------------------
echo -e "   - Renumber mesh for speedup (~5-15%)"
mpirun -np 4 renumberMesh -overwrite -parallel >> logSolver


#------------------------------------------------------------------------------
echo -e "   - Start steady-state calculation (5 to 60 minutes)"
mpirun -np 4 foamRun -parallel >> logSolver


#------------------------------------------------------------------------------
echo -e "   - Simulation ended\n\n"


#------------------------------------------------------------------------------
